apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman
    app.kubernetes.io/part-of: mongo-pacman
  name: pacman
  namespace: jduimovich-tenant
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: pacman
    weight: null
status: {}
